// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-gyXkqtFg0jJcEzHJPZ6UoDdAqgSDt7U',
    appId: '1:154078396326:web:f7f82441e2b93b7d17d967',
    messagingSenderId: '154078396326',
    projectId: 'easyshopping-cbcd2',
    authDomain: 'easyshopping-cbcd2.firebaseapp.com',
    storageBucket: 'easyshopping-cbcd2.appspot.com',
    measurementId: 'G-5Y7TB5QWCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaJ38s2vzkWP9CqMngl3LVpr42yj96vC0',
    appId: '1:154078396326:android:ebedd14515c6606517d967',
    messagingSenderId: '154078396326',
    projectId: 'easyshopping-cbcd2',
    storageBucket: 'easyshopping-cbcd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKKmWyW5opjo4DdRCGtVLHrbhP9xsyM7o',
    appId: '1:154078396326:ios:7d6706f6c593400717d967',
    messagingSenderId: '154078396326',
    projectId: 'easyshopping-cbcd2',
    storageBucket: 'easyshopping-cbcd2.appspot.com',
    iosBundleId: 'com.example.aECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKKmWyW5opjo4DdRCGtVLHrbhP9xsyM7o',
    appId: '1:154078396326:ios:7d6706f6c593400717d967',
    messagingSenderId: '154078396326',
    projectId: 'easyshopping-cbcd2',
    storageBucket: 'easyshopping-cbcd2.appspot.com',
    iosBundleId: 'com.example.aECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-gyXkqtFg0jJcEzHJPZ6UoDdAqgSDt7U',
    appId: '1:154078396326:web:d30c8fa8ab03c1cf17d967',
    messagingSenderId: '154078396326',
    projectId: 'easyshopping-cbcd2',
    authDomain: 'easyshopping-cbcd2.firebaseapp.com',
    storageBucket: 'easyshopping-cbcd2.appspot.com',
    measurementId: 'G-TE3XTLBRH6',
  );

}